home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    # path('signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.display_tasks, name='display-tasks'),
    path('task_details/<int:task_id>/', views.task_details, name='task-details'),
    path('edit/<int:task_id>/', views.edit_task, name='edit-task'),
    path('delete/<int:task_id>/', views.delete_task, name='delete-task'),
    path('clear-all/', views.clear_all, name='clear-all'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _ 
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager


class TodoUserManager(BaseUserManager):
    def create_user(self, email, username, firstname, lastname, password, **other_fields):
        
        if not email:
            raise ValueError(_('You must provide an email address'))
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, firstname=firstname, lastname=lastname, **other_fields)
        user.set_password(password)
        user.save()
        
        return user
    
    def create_superuser(self, email, username, firstname, lastname, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        
        if not other_fields.get('is_staff'):
            raise ValueError('Superuser must be assigned to is_staff=True.')
        
        if not other_fields.get('is_superuser'):
            raise ValueError('Superuser must be assigned to is_superuser=True.')
        
        return self.create_user(email, username, firstname, lastname, password, **other_fields)
        


class TodoUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email adress'), unique=True)
    username = models.CharField(max_length=150, unique=True)
    firstname = models.CharField(max_length=150, blank=True, null=True)
    lastname = models.CharField(max_length=150, blank=True, null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'firstname', 'lastname']
    
    objects = TodoUserManager()
    
    def __str__(self):
        return self.username

tasks/models.py
from django.db import models
from home.models import TodoUser


class Task(models.Model):
    STATUS_CHOICES = (
        ('completed', 'completed'),
        ('not completed', 'not completed'),
    )
    
    title = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True, null=True)
    assigned_user = models.ForeignKey(TodoUser, on_delete=models.CASCADE, related_name='tasks')
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=13, choices=STATUS_CHOICES, default='not completed')
    
    def __str__(self):
        return self.title

home/forms.py
from django import forms
from .models import TodoUser


class LoginForm(forms.ModelForm):
    class Meta:
        model = TodoUser
        fields = ('email', 'password')
        

class SignupForm(forms.ModelForm):
    class Meta:
        model = TodoUser
        fields = ('username', 'firstname', 'lastname', 'email', 'password', 'password')

tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ('title', 'description', 'status')
        
        labels = {
            'title': '',
            'description': '',
            'status': 'Did you complete this task?',
        }
        
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'border-2 border-gray-300 rounded py-2 w-full placeholder:text-sm px-4',
                    'placeholder': 'Task title',
                }
                ),
            'description': forms.Textarea(
                attrs={
                    'class': 'border-2 border-gray-300 rounded py-2 w-full placeholder:text-sm px-4 mt-2',
                    'placeholder': 'Task description',
                    'rows': 5,
                    'cols': 33,
                }    
            ),
            'status': forms.RadioSelect(
                attrs={
                    'class': 'h-4 w-4 text-indigo-600 focus:ring-indigo-500 cursor-pointer border-gray-300 inline',
                }
            ),
        }
        
        error_messages = {
            'title': {
                'required': 'Please Enter a task title',
                'invalid': 'this is an invalid task title'
            }
        }

home/views.py
from django.shortcuts import render
from .forms import LoginForm, SignupForm


# def index(request):
#     return render(request, 'home/index.html')


def login(request):
    form = LoginForm()
    return render(request, 'home/login.html', {'form': form})


def signup(request):
    form = SignupForm()
    return render(request, 'home/index.html', {'form': form})


def about(request):
    return render(request, 'home/about.html')

tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import TaskForm
from .models import Task


def display_tasks(request):
    tasks = Task.objects.all()
    
    if request.method == 'POST':
        if request.POST.get('title'):
            new_task = Task(
                title=request.POST.get('title'),
                assigned_user=request.user,            
            )
            new_task.save()
        return redirect('tasks:display-tasks')
    
    context = {
        'tasks': tasks,
    }
    return render(request, 'tasks/tasks.html', context)


def task_details(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    context = {
        'task': task,
    }
    return render(request, 'tasks/task_details.html', context)


def edit_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
        return redirect('tasks:display-tasks')
    
    form = TaskForm(instance=task)
    context = {
        'form': form,
    }
    return render(request, 'tasks/edit_task.html', context)


def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks:display-tasks')
    
    context = {
        'task': task,
    }
    return render(request, 'tasks/delete_task.html', context)


def clear_all(request):
    tasks = Task.objects.all()
    if request.method == 'POST':
        tasks.delete()
        return redirect('tasks:display-tasks')
    
    context = {
        'tasks': tasks,
    }
    
    return render(request, 'tasks/clear_all.html', context)

home/templates/home/index.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% include 'partials/user_profile.html' %}
    {% else %}
        <div class="max-h-full bg-gray-200 border border-gray-300 rounded p-4 w-full max-w-screen-sm overflow-auto">

            <div class="mt-2 ml-2 md:ml-14 sm:ml-5 mr-2">
                <div class="">
                    <svg class="fill-current w-8 h-8" version="1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" enable-background="new 0 0 48 48">
                        <g fill="#3F51B5">
                            <polygon points="17.8,18.1 10.4,25.4 6.2,21.3 4,23.5 10.4,29.9 20,20.3"/>
                            <polygon points="17.8,5.1 10.4,12.4 6.2,8.3 4,10.5 10.4,16.9 20,7.3"/>
                            <polygon points="17.8,31.1 10.4,38.4 6.2,34.3 4,36.5 10.4,42.9 20,33.3"/>
                        </g>
                        <g fill="#90CAF9">
                            <rect x="24" y="22" width="20" height="4"/>
                            <rect x="24" y="9" width="20" height="4"/>
                            <rect x="24" y="35" width="20" height="4"/>
                        </g>
                    </svg>
                </div>
                <div class="my-1 text-3xl text-gray-900">
                    Sign up
                </div>
                <div class="text-xs text-gray-500">
                    Enter your details below to create your account and get started.
                </div>
            </div>

            <div class="ml-2 mr-2 mb-2 mt-1">
                <form method="post" class="flex-col justify-center align-center">
                    {% csrf_token %}
                    
                    <div class="sm:flex sm:justify-around sm:align-center sm:mt-4">
                        
                        <div class="">
                            <div class="text-sm text-gray-700">
                                <label>Username</label>
                            </div>
                            {% render_field form.username class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" placeholder="enter..." %}
                        </div>
                        
                        <div class=" mt-2 sm:mt-0">
                            <div class="text-sm text-gray-700">
                                <label>Email adress</label>
                            </div>
                            {% render_field form.email class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" placeholder="example@gmail.com" %}
                        </div>

                    </div>

                    <div class="sm:flex sm:justify-around sm:align-center sm:mt-4">
                        
                        <div class=" mt-2 sm:mt-0">
                            <div class="text-sm text-gray-700">
                                <label>Firstname</label>
                            </div>
                            {% render_field form.firstname class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" placeholder="enter..." %}
                        </div>
                        
                        <div class=" mt-2 sm:mt-0">
                            <div class="text-sm text-gray-700">
                                <label>Lastname</label>
                            </div>
                            {% render_field form.lastname class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" placeholder="enter..." %}
                        </div>

                    </div>

                    <div class="sm:flex sm:justify-around sm:align-center sm:mt-4">
                        
                        <div class=" mt-2 sm:mt-0">
                            <div class="text-sm text-gray-700">
                                <label>Password</label>
                            </div>
                            {% render_field form.password class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" type="password" placeholder="enter..." %}
                        </div>
                        
                        <div class=" mt-2 sm:mt-0">
                            <div class="text-sm text-gray-700">
                                <label>Confirm password</label>
                            </div>
                            {% render_field form.password class="placeholder:text-sm mt-2 py-1 px-2 w-full rounded border border-gray-300" type="password" placeholder="enter..." %}
                        </div>

                    </div>

                    <div class="sm:flex sm:flex-row-reverse sm:justify-around sm:mt-4">
                        
                        <div class=" mt-2 sm:mt-0">
                            <button class="sm:px-20 mt-4 hover:bg-indigo-500 rounded w-full py-2 hover:text-gray-200 bg-indigo-700 text-white w-full">Confirm</button>
                        </div>

                        <div class=" mt-2 sm:mt-0">
                            <button class="sm:px-20 mt-4 hover:bg-red-600 rounded py-2 border border-gray-300 text-gray-900 w-full">Cancel</button>
                        </div>

                    </div>

                    <div class="md:ml-14 sm:ml-5 sm:mt-4 mt-2 sm:mt-0 text-xs text-gray-500">
                        Already have an account? <a class="text-indigo-700" href="{% url 'home:login' %}">Login</a>
                    </div>

                </form>
            </div>

        </div>
    {% endif %}
{% endblock %}

home/templates/home/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="max-h-full bg-gray-200 border border-gray-300 rounded p-4 w-full max-w-screen-sm">
        <div class="overflow-auto">
            <div class="mt-4 flex justify-center items-center">
                <svg class="fill-current w-8 h-8" version="1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" enable-background="new 0 0 48 48">
                    <g fill="#3F51B5">
                        <polygon points="17.8,18.1 10.4,25.4 6.2,21.3 4,23.5 10.4,29.9 20,20.3"/>
                        <polygon points="17.8,5.1 10.4,12.4 6.2,8.3 4,10.5 10.4,16.9 20,7.3"/>
                        <polygon points="17.8,31.1 10.4,38.4 6.2,34.3 4,36.5 10.4,42.9 20,33.3"/>
                    </g>
                    <g fill="#90CAF9">
                        <rect x="24" y="22" width="20" height="4"/>
                        <rect x="24" y="9" width="20" height="4"/>
                        <rect x="24" y="35" width="20" height="4"/>
                    </g>
                </svg>
            </div>
            <div class="flex justify-center items-center text-3xl text-gray-900 mt-2">Welcome back</div>
            <div class="flex justify-center items-center text-xs text-gray-500 mt-2">Glad to see you again &#128075;</div>
            <div class="flex justify-center items-center text-xs text-gray-500">Login to your account below</div>
        </div>
        <div class="flex justify-center items-center">
            <a href="" class="mt-3 border-2 border-gray-300 rounded-xl w-full sm:w-2/3 flex justify-center items-center py-2 hover:bg-gray-300">
                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="48" height="48" viewBox="0 0 48 48">
                    <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path><path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path><path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path><path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
                    </svg>
                <span class="text-xs font-semibold">
                    Continue with Google
                </span>
            </a> 
        </div>
        <div class="flex justify-center items-center mt-4">
            <form method="post">
                {% csrf_token %}
                
                <div class="mt-4">
                    <div class="text-sm text-gray-500 select-none">
                        <label>Email</label>
                    </div>
                    {% render_field form.email class="border-2 border-gray-300 rounded py-2 w-full placeholder:text-sm px-4" placeholder="enter email..." %}
                </div>
                
                <div class="mt-4">
                    <div class="text-sm text-gray-500 select-none">
                        <label>Password</label>
                    </div>
                    {% render_field form.password class="border-2 border-gray-300 rounded py-2 w-full placeholder:text-sm px-4" placeholder="enter password..." %}
                </div>

                <button class="mt-4 hover:bg-indigo-500 rounded w-full py-2 hover:text-gray-200 bg-indigo-700 text-white">Login</button>
                <div class="text-xs text-gray-500 mt-4">
                    Don't have an accout? <a class="text-indigo-700" href="{% url 'home:signup' %}">Sign up for Free</a>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

tasks/templates/tasks/delete.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

{% endblock %}

tasks/templates/tasks/task_details.html
{% extends 'base.html' %}

{% block title %}Task Details{% endblock %}

{% block content %}
    <div class="max-h-full flex-col bg-gray-200 border border-gray-300 rounded p-4 sm:p-8 w-full max-w-screen-sm overflow-auto">
        <div class="text-2xl sm:text-3xl font-semibold text-gray-900">
            {{ task }} ({{ task.status }})
        </div>
        <div class="flex items-center flex-wrap mt-2">
            <div class="flex items-center bg-gray-300 rounded px-2 py-1 w-fit h-7 mt-1 select-none">
                <svg class="fill-current" height="20px" version="1.1" viewBox="0 0 20 20" width="18px" xmlns="http://www.w3.org/2000/svg" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns:xlink="http://www.w3.org/1999/xlink"><title/><desc/><defs/><g fill="none" fill-rule="evenodd" id="Page-1" stroke="none" stroke-width="1"><g fill="#000000" id="Core" transform="translate(-339.000000, -464.000000)"><g id="today" transform="translate(339.000000, 464.000000)"><path d="M16,2 L15,2 L15,0 L13,0 L13,2 L5,2 L5,0 L3,0 L3,2 L2,2 C0.9,2 0,2.9 0,4 L0,18 C0,19.1 0.9,20 2,20 L16,20 C17.1,20 18,19.1 18,18 L18,4 C18,2.9 17.1,2 16,2 L16,2 Z M16,18 L2,18 L2,7 L16,7 L16,18 L16,18 Z" id="Shape"/><rect height="5" id="Rectangle-path" width="5" x="4" y="9"/></g></g></g></svg>
                <div class="text-sm text-gray-700 ml-1">
                    {{ task.created_at|date:"Y-m-d" }}
                </div>
            </div>
            <div class="flex items-center bg-gray-300 ml-2 rounded px-2 py-1 w-fit h-7 mt-1 select-none">
                <svg class="fill-current w-5 h-5" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><defs><style>.cls-1{fill:#101820;}</style></defs><title/><g data-name="Layer 15" id="Layer_15"><path class="cls-1" d="M16,31A15,15,0,1,1,31,16,15,15,0,0,1,16,31ZM16,3A13,13,0,1,0,29,16,13,13,0,0,0,16,3Z"/><path class="cls-1" d="M20.24,21.66l-4.95-4.95A1,1,0,0,1,15,16V8h2v7.59l4.66,4.65Z"/></g></svg>
                <div class="text-sm text-gray-700 ml-1">
                    {{ task.created_at|date:"H:i" }}
                </div>
            </div>
            <a href="{% url 'home:signup' %}">
                <div class="flex items-center bg-gray-300 ml-2 rounded px-2 py-1 w-fit h-7 mt-1 select-none">                
                    <svg class="fill-current w-7 h-7" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 30"><path d="M12,10.91c2.11,0,3.83-1.72,3.83-3.83s-1.72-3.83-3.83-3.83-3.83,1.72-3.83,3.83,1.72,3.83,3.83,3.83Z"/><path d="M6.21,20.75h11.58c.69,0,1.25-.56,1.25-1.25v-2.09c0-2.75-2.24-5-5-5h-4.08c-2.76,0-5,2.25-5,5v2.09c0,.69,.56,1.25,1.25,1.25Z"/></svg>
                    <div class="text-sm text-gray-700">
                        {{ task.assigned_user }}
                    </div>
                </div>
            </a>
        </div>
        {% if task.description %}
            <div class="mt-2 text-xl sm:text-2xl text-gray-900">
                Description
            </div>
            <div class="text-sm text-gray-700">
                {{ task.description }}
            </div>
        {% endif %}
    </div>
{% endblock %}

tasks/templates/tasks/tasks.html
{% extends 'base.html' %}

{% block title %}Todo App | username{% endblock %}

{% block content %}
    <div class="max-h-full flex-col bg-gray-200 border border-gray-300 rounded p-4 w-full max-w-screen-sm overflow-auto">
        <div class="flex items-center">
            <div class="">
                <!-- todo app logo -->
                <svg class="fill-current w-8 h-8" version="1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" enable-background="new 0 0 48 48">
                    <g fill="#3F51B5">
                        <polygon points="17.8,18.1 10.4,25.4 6.2,21.3 4,23.5 10.4,29.9 20,20.3"/>
                        <polygon points="17.8,5.1 10.4,12.4 6.2,8.3 4,10.5 10.4,16.9 20,7.3"/>
                        <polygon points="17.8,31.1 10.4,38.4 6.2,34.3 4,36.5 10.4,42.9 20,33.3"/>
                    </g>
                    <g fill="#90CAF9">
                        <rect x="24" y="22" width="20" height="4"/>
                        <rect x="24" y="9" width="20" height="4"/>
                        <rect x="24" y="35" width="20" height="4"/>
                    </g>
                </svg>            
            </div>
            <div class="font-black text-3xl text-gray-900 ml-2">
                Todo App
            </div>
        </div>
        <div class="mt-2">
            <form class="flex items-center" method="post">
                {% csrf_token %}
                <!-- input for new task title -->
                <input type="text" name="title" class="bg-gray-100 border border-gray-300 w-full rounded px-2 py-1" placeholder="Add your new todo">
                <!-- button to add a new task -->
                <button type="submit">
                    <a href="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" class="fill-current h-10 w-10 text-green-500 hover:text-green-700"><g id="Layer_55" data-name="Layer 55"><path class="fill-current" d="M52,10.5H12A1.5,1.5,0,0,0,10.5,12V52A1.5,1.5,0,0,0,12,53.5H52A1.5,1.5,0,0,0,53.5,52V12A1.5,1.5,0,0,0,52,10.5Zm-7.17,23H33.5V44.83a1.5,1.5,0,0,1-3,0V33.5H19.17a1.5,1.5,0,0,1,0-3H30.5V19.17a1.5,1.5,0,0,1,3,0V30.5H44.83A1.5,1.5,0,0,1,44.83,33.5Z"/></g></svg>
                    </a>
                </button>
            </form>
        </div>
        <div class="flex-col my-2">
            {% for task in tasks %}
                <a href="{% url 'tasks:task-details' task.id %}" class="">
                    <div class="bg-gray-300 text-gray-900 text-sm rounded py-2 px-1 flex justify-between 
                    {% if forloop.counter != 1 %}
                        mt-2
                    {% endif %}
                    ">
                            <div class="inline-block">{{ task }}</div>
                            <div class="flex">
                                <!-- Edit button -->
                                <a href="{% url 'tasks:edit-task' task.id %}" class="">
                                    <svg class="fill-current text-indigo-500 hover:text-indigo-900 w-8" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="21" height="21" viewBox="0 0 128 128">
                                        <path d="M 79.335938 15.667969 C 78.064453 15.622266 76.775 15.762109 75.5 16.099609 C 72.1 16.999609 69.299609 19.199219 67.599609 22.199219 L 64 28.699219 C 63.2 30.099219 63.699609 32.000781 65.099609 32.800781 L 82.400391 42.800781 C 82.900391 43.100781 83.400391 43.199219 83.900391 43.199219 C 84.200391 43.199219 84.399219 43.199609 84.699219 43.099609 C 85.499219 42.899609 86.1 42.399219 86.5 41.699219 L 90.199219 35.199219 C 91.899219 32.199219 92.4 28.700781 91.5 25.300781 C 90.6 21.900781 88.400391 19.100391 85.400391 17.400391 C 83.525391 16.337891 81.455078 15.744141 79.335938 15.667969 z M 60.097656 38.126953 C 59.128906 38.201172 58.199219 38.724609 57.699219 39.599609 L 27.5 92 C 24.1 97.8 22.200781 104.30039 21.800781 110.90039 L 21 123.80078 C 20.9 124.90078 21.5 125.99961 22.5 126.59961 C 23 126.89961 23.5 127 24 127 C 24.6 127 25.199219 126.8 25.699219 126.5 L 36.5 119.40039 C 42 115.70039 46.7 110.8 50 105 L 80.300781 52.599609 C 81.100781 51.199609 80.599219 49.3 79.199219 48.5 C 77.799219 47.7 75.899609 48.199609 75.099609 49.599609 L 44.800781 102 C 41.900781 106.9 37.899609 111.20039 33.099609 114.40039 L 27.300781 118.19922 L 27.699219 111.30078 C 27.999219 105.60078 29.699609 100 32.599609 95 L 62.900391 42.599609 C 63.700391 41.199609 63.200781 39.3 61.800781 38.5 C 61.275781 38.2 60.678906 38.082422 60.097656 38.126953 z M 49 121 C 47.3 121 46 122.3 46 124 C 46 125.7 47.3 127 49 127 L 89 127 C 90.7 127 92 125.7 92 124 C 92 122.3 90.7 121 89 121 L 49 121 z M 104 121 A 3 3 0 0 0 101 124 A 3 3 0 0 0 104 127 A 3 3 0 0 0 107 124 A 3 3 0 0 0 104 121 z"></path>
                                    </svg>
                                </a>
                                <!-- delete button -->
                                <a href="{% url 'tasks:delete-task' task.id %}" class="">
                                    <svg class="text-red-500 hover:text-red-700" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24">
                                        <path class="fill-current" d="M 10 2 L 9 3 L 4 3 L 4 5 L 20 5 L 20 3 L 15 3 L 14 2 L 10 2 z M 5 7 L 5 22 L 19 22 L 19 7 L 5 7 z M 8 9 L 10 9 L 10 20 L 8 20 L 8 9 z M 14 9 L 16 9 L 16 20 L 14 20 L 14 9 z"></path>
                                    </svg>
                                </a>
                            </div>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="flex justify-between items-center mt-4">
            <div class="text-sm">You have {{ tasks.count }} pending task{{ tasks.count|pluralize }}</div>
            <!-- clear all button -->
            <a href="{% url 'tasks:clear-all' %}" class="bg-green-500 text-gray-100 hover:bg-green-700 px-2 py-1 rounded text-center text-sm font-medium">Clear All</a>
        </div>
    </div>
{% endblock %}

templates/partials/navbar.html
<div class="w-3/4 bg-gray-200 py-3 border border-gray-300 mt-4 rounded flex justify-center absolute top-0 max-w-screen-sm">
    <ul class="flex items-center flex-wrap">
        <li class="px-2">
            <span class="text-sm text-gray-400 font-semibold select-none">Todo</span>
        </li>
        <li class="px-2">
            <a class="text-sm text-gray-400 hover:text-gray-900 select-none" href="{% url 'home:signup' %}">Home</a>
        </li>
        <li class="px-2">
            <a class="text-sm text-gray-400 hover:text-gray-900 select-none" href="{% url 'home:about' %}">About</a>
        </li>
        <li class="px-2">
            {% if user.is_authenticated %}
                <a class="text-sm text-gray-400 hover:text-gray-900 select-none" href="#">Logout</a>
            {% else %}
                <a class="text-sm text-gray-400 hover:text-gray-900 select-none" href="{% url 'home:login' %}">Login</a>
            {% endif %}
        </li>
    </ul>
</div>